dataset:
    root: "./data"
    name: "cifar10"
    path: "cifar10_data"
    resolution: 32
    num_classes: 10

model:
    in_channels: 3
    out_channels: ${out_channels:${model.mean_type}}
    channels: 128
    channel_multiplier: [1, 2, 2, 2]
    n_res_blocks: 2
    attn_strides: [2]
    mean_type: dualx
    var_type: fixedlarge
    is_implicit: True
    dropout: 0.1
    fold: 1
    schedule:
        type: linear
        beta_start: 1.e-4
        beta_end: 2.e-2
        cosine_temp1: 1
        cosine_temp2: 2
        n_timestep: 1000

training:
    n_iter: 1000000
    n_epochs: -1
    ema:
        start_epoch: 0
        decay: 0.9999
    optimizer:
        type: adam
        lr: 2.e-4
        wd: 0.0
    dataloader:
        batch_size: 128
        num_workers: 8
    accumulate_grad_batches: 1

validation:
    dataloader:
        batch_size: 100
        num_workers: 8
